/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControllerDueno;
import controlador.ControllerUsuario;
import javax.swing.JOptionPane;

/**
 *
 * @author JOSH
 */
public class frmDueno extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmDueno
     */
    public frmDueno() {
        initComponents();
        setTitle("Ventana Dueños");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMantMasc = new javax.swing.JPanel();
        lblTitleDuenos = new javax.swing.JLabel();
        panelDetalleDue = new javax.swing.JPanel();
        lblBuscarNombreClientes = new javax.swing.JLabel();
        btnBuscarDue = new javax.swing.JButton();
        txtBuscarNombreDue = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDueno = new javax.swing.JTable();
        btnEliminarDueno = new javax.swing.JButton();
        btnRefrescarDueno = new javax.swing.JButton();
        panelIngresarDatosDue = new javax.swing.JPanel();
        lblIdDuenofrm = new javax.swing.JLabel();
        lblNombreDueno = new javax.swing.JLabel();
        lbl1ApellidoDue = new javax.swing.JLabel();
        txtIdDuenoFrm = new javax.swing.JTextField();
        txtNombreDueno = new javax.swing.JTextField();
        lbl2ApellidoDue = new javax.swing.JLabel();
        lblCedulaDue = new javax.swing.JLabel();
        btnCancelarDueno = new javax.swing.JButton();
        btnGuardarDueno = new javax.swing.JButton();
        btnEditarDueno = new javax.swing.JButton();
        lblGeneroDue = new javax.swing.JLabel();
        cboxGeneroDue = new javax.swing.JComboBox<>();
        lblEmailDue = new javax.swing.JLabel();
        txtEmailDue = new javax.swing.JTextField();
        txt1ApellidoDue = new javax.swing.JTextField();
        txt2ApellidoDue = new javax.swing.JTextField();
        txtCedulaDue = new javax.swing.JTextField();
        lblTelfDue = new javax.swing.JLabel();
        txtTelfDue = new javax.swing.JTextField();
        lblDireccionDue = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDireccionDue = new javax.swing.JTextArea();
        lblLogoDue = new javax.swing.JLabel();
        lblLogoDueno = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Ventana Dueños");

        panelMantMasc.setBackground(new java.awt.Color(255, 255, 255));
        panelMantMasc.setForeground(new java.awt.Color(255, 255, 255));

        lblTitleDuenos.setFont(new java.awt.Font("SansSerif", 3, 22)); // NOI18N
        lblTitleDuenos.setText("MANTENIMIENTO DE DUEÑOS");

        panelDetalleDue.setBackground(new java.awt.Color(255, 255, 255));
        panelDetalleDue.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12))); // NOI18N

        lblBuscarNombreClientes.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblBuscarNombreClientes.setText("Buscar por Nombre:");

        btnBuscarDue.setBackground(new java.awt.Color(255, 153, 0));
        btnBuscarDue.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnBuscarDue.setText("BUSCAR");
        btnBuscarDue.setToolTipText("Busca por nombre el dueño en la tabla");

        txtBuscarNombreDue.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N

        tableDueno.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tableDueno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID DE DUEÑO", "NOMBRE", "PRIMER APELLIDO", "SEGUNDO APELLIDO", "CÉDULA", "GÉNERO", "E-MAIL", "TELÉFONO", "DIRECCIÓN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableDueno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDuenoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDueno);
        if (tableDueno.getColumnModel().getColumnCount() > 0) {
            tableDueno.getColumnModel().getColumn(0).setResizable(false);
            tableDueno.getColumnModel().getColumn(1).setResizable(false);
            tableDueno.getColumnModel().getColumn(2).setResizable(false);
            tableDueno.getColumnModel().getColumn(3).setResizable(false);
            tableDueno.getColumnModel().getColumn(4).setResizable(false);
            tableDueno.getColumnModel().getColumn(5).setResizable(false);
            tableDueno.getColumnModel().getColumn(6).setResizable(false);
            tableDueno.getColumnModel().getColumn(7).setResizable(false);
            tableDueno.getColumnModel().getColumn(8).setResizable(false);
        }

        btnEliminarDueno.setBackground(new java.awt.Color(35, 61, 83));
        btnEliminarDueno.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnEliminarDueno.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarDueno.setText("ELIMINAR");
        btnEliminarDueno.setToolTipText("Elimina un dueño de la tabla");

        btnRefrescarDueno.setBackground(new java.awt.Color(6, 75, 115));
        btnRefrescarDueno.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnRefrescarDueno.setForeground(new java.awt.Color(255, 255, 255));
        btnRefrescarDueno.setText("REFRESCAR");
        btnRefrescarDueno.setToolTipText("Refresca la tabla");

        javax.swing.GroupLayout panelDetalleDueLayout = new javax.swing.GroupLayout(panelDetalleDue);
        panelDetalleDue.setLayout(panelDetalleDueLayout);
        panelDetalleDueLayout.setHorizontalGroup(
            panelDetalleDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetalleDueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetalleDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetalleDueLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRefrescarDueno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarDueno))
                    .addGroup(panelDetalleDueLayout.createSequentialGroup()
                        .addGroup(panelDetalleDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDetalleDueLayout.createSequentialGroup()
                                .addComponent(lblBuscarNombreClientes)
                                .addGap(18, 18, 18)
                                .addComponent(txtBuscarNombreDue, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarDue, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDetalleDueLayout.setVerticalGroup(
            panelDetalleDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetalleDueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetalleDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarNombreClientes)
                    .addComponent(btnBuscarDue)
                    .addComponent(txtBuscarNombreDue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelDetalleDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefrescarDueno)
                    .addComponent(btnEliminarDueno))
                .addContainerGap())
        );

        panelIngresarDatosDue.setBackground(new java.awt.Color(255, 255, 255));
        panelIngresarDatosDue.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingresar Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12))); // NOI18N

        lblIdDuenofrm.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblIdDuenofrm.setText("ID de Dueño:");

        lblNombreDueno.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblNombreDueno.setText("Nombre:");

        lbl1ApellidoDue.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lbl1ApellidoDue.setText("Primer Apellido:");

        txtIdDuenoFrm.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtIdDuenoFrm.setToolTipText("");

        txtNombreDueno.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtNombreDueno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreDuenoActionPerformed(evt);
            }
        });

        lbl2ApellidoDue.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lbl2ApellidoDue.setText("Segundo Apellido:");

        lblCedulaDue.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblCedulaDue.setText("Cédula:");

        btnCancelarDueno.setBackground(new java.awt.Color(35, 61, 83));
        btnCancelarDueno.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnCancelarDueno.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarDueno.setText("CANCELAR");
        btnCancelarDueno.setToolTipText("Cancela las acciones");

        btnGuardarDueno.setBackground(new java.awt.Color(255, 153, 0));
        btnGuardarDueno.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnGuardarDueno.setText("GUARDAR");
        btnGuardarDueno.setToolTipText("Guardar los cambios");

        btnEditarDueno.setBackground(new java.awt.Color(254, 189, 105));
        btnEditarDueno.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnEditarDueno.setText("EDITAR");
        btnEditarDueno.setToolTipText("Actualiza nueva información del dueño");

        lblGeneroDue.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblGeneroDue.setText("Género:");

        cboxGeneroDue.setBackground(new java.awt.Color(102, 102, 102));
        cboxGeneroDue.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        cboxGeneroDue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MASCULINO", "FEMENINO", "OTRO" }));

        lblEmailDue.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblEmailDue.setText("E-mail:");

        txtEmailDue.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtEmailDue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailDueActionPerformed(evt);
            }
        });

        txt1ApellidoDue.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txt1ApellidoDue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ApellidoDueActionPerformed(evt);
            }
        });

        txt2ApellidoDue.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txt2ApellidoDue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ApellidoDueActionPerformed(evt);
            }
        });

        txtCedulaDue.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtCedulaDue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaDueActionPerformed(evt);
            }
        });

        lblTelfDue.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblTelfDue.setText("Teléfono:");

        txtTelfDue.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtTelfDue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelfDueActionPerformed(evt);
            }
        });

        lblDireccionDue.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblDireccionDue.setText("Dirección:");

        txtDireccionDue.setColumns(20);
        txtDireccionDue.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtDireccionDue.setRows(5);
        jScrollPane2.setViewportView(txtDireccionDue);

        javax.swing.GroupLayout panelIngresarDatosDueLayout = new javax.swing.GroupLayout(panelIngresarDatosDue);
        panelIngresarDatosDue.setLayout(panelIngresarDatosDueLayout);
        panelIngresarDatosDueLayout.setHorizontalGroup(
            panelIngresarDatosDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarDatosDueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIngresarDatosDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIngresarDatosDueLayout.createSequentialGroup()
                        .addGroup(panelIngresarDatosDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdDuenofrm)
                            .addComponent(lblNombreDueno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelIngresarDatosDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdDuenoFrm, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(txtNombreDueno)))
                    .addGroup(panelIngresarDatosDueLayout.createSequentialGroup()
                        .addGroup(panelIngresarDatosDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCedulaDue)
                            .addComponent(lblGeneroDue))
                        .addGap(71, 71, 71)
                        .addGroup(panelIngresarDatosDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCedulaDue)
                            .addComponent(cboxGeneroDue, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelIngresarDatosDueLayout.createSequentialGroup()
                        .addGroup(panelIngresarDatosDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl1ApellidoDue)
                            .addComponent(lbl2ApellidoDue))
                        .addGap(23, 23, 23)
                        .addGroup(panelIngresarDatosDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt2ApellidoDue)
                            .addComponent(txt1ApellidoDue)))
                    .addGroup(panelIngresarDatosDueLayout.createSequentialGroup()
                        .addComponent(lblEmailDue)
                        .addGap(79, 79, 79)
                        .addComponent(txtEmailDue))
                    .addGroup(panelIngresarDatosDueLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnGuardarDueno, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarDueno, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarDueno, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelIngresarDatosDueLayout.createSequentialGroup()
                        .addGroup(panelIngresarDatosDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelfDue)
                            .addComponent(lblDireccionDue))
                        .addGap(62, 62, 62)
                        .addGroup(panelIngresarDatosDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelfDue)
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );
        panelIngresarDatosDueLayout.setVerticalGroup(
            panelIngresarDatosDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarDatosDueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIngresarDatosDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdDuenofrm)
                    .addComponent(txtIdDuenoFrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelIngresarDatosDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreDueno)
                    .addComponent(txtNombreDueno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1ApellidoDue)
                    .addComponent(txt1ApellidoDue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2ApellidoDue)
                    .addComponent(txt2ApellidoDue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedulaDue)
                    .addComponent(txtCedulaDue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelIngresarDatosDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGeneroDue)
                    .addComponent(cboxGeneroDue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailDue)
                    .addComponent(txtEmailDue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelIngresarDatosDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelfDue)
                    .addComponent(txtTelfDue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDireccionDue)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(panelIngresarDatosDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarDueno)
                    .addComponent(btnEditarDueno)
                    .addComponent(btnCancelarDueno))
                .addContainerGap())
        );

        lblLogoDueno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rsz_2mimasc2.jpg"))); // NOI18N
        lblLogoDueno.setText("jLabel1");

        javax.swing.GroupLayout panelMantMascLayout = new javax.swing.GroupLayout(panelMantMasc);
        panelMantMasc.setLayout(panelMantMascLayout);
        panelMantMascLayout.setHorizontalGroup(
            panelMantMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMantMascLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMantMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelIngresarDatosDue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitleDuenos))
                .addGroup(panelMantMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMantMascLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelDetalleDue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMantMascLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLogoDueno, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLogoDue)
                        .addGap(316, 316, 316))))
        );
        panelMantMascLayout.setVerticalGroup(
            panelMantMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMantMascLayout.createSequentialGroup()
                .addGroup(panelMantMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelMantMascLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelDetalleDue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMantMascLayout.createSequentialGroup()
                        .addContainerGap(12, Short.MAX_VALUE)
                        .addGroup(panelMantMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelMantMascLayout.createSequentialGroup()
                                .addComponent(lblTitleDuenos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelIngresarDatosDue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelMantMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelMantMascLayout.createSequentialGroup()
                                    .addGap(0, 63, Short.MAX_VALUE)
                                    .addComponent(lblLogoDue)
                                    .addGap(427, 427, 427))
                                .addComponent(lblLogoDueno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMantMasc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMantMasc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableDuenoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDuenoMouseClicked
   try{
        
            int fila = tableDueno.getSelectedRow();
            txtIdDuenoFrm.setText(tableDueno.getValueAt(fila, 0).toString());
            txtNombreDueno.setText(tableDueno.getValueAt(fila, 1).toString());
            txt1ApellidoDue.setText(tableDueno.getValueAt(fila, 2).toString());
            txt2ApellidoDue.setText(tableDueno.getValueAt(fila, 3).toString());
            txtCedulaDue.setText(tableDueno.getValueAt(fila, 4).toString());
            cboxGeneroDue.setSelectedItem(tableDueno.getValueAt(fila, 5));
            txtEmailDue.setText(tableDueno.getValueAt(fila, 6).toString());
            txtTelfDue.setText(tableDueno.getValueAt(fila, 7).toString());
            txtDireccionDue.setText(tableDueno.getValueAt(fila, 8).toString());
            
            
        }catch (Exception e){
        
            JOptionPane.showMessageDialog(this, "ERROR AL SELECCIONAR UN REGISTRO:" + e.getMessage());
            
        }     
    }//GEN-LAST:event_tableDuenoMouseClicked

    private void txtNombreDuenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreDuenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreDuenoActionPerformed

    private void txtEmailDueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailDueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailDueActionPerformed

    private void txt1ApellidoDueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ApellidoDueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ApellidoDueActionPerformed

    private void txt2ApellidoDueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ApellidoDueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2ApellidoDueActionPerformed

    private void txtCedulaDueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaDueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaDueActionPerformed

    private void txtTelfDueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelfDueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelfDueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDueno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDueno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDueno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDueno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                  frmDueno due = new frmDueno();
                ControllerDueno con = new ControllerDueno(due);
                con.iniciar();
                due.setVisible(true);
                due.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarDue;
    public javax.swing.JButton btnCancelarDueno;
    public javax.swing.JButton btnEditarDueno;
    public javax.swing.JButton btnEliminarDueno;
    public javax.swing.JButton btnGuardarDueno;
    public javax.swing.JButton btnRefrescarDueno;
    public javax.swing.JComboBox<String> cboxGeneroDue;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lbl1ApellidoDue;
    public javax.swing.JLabel lbl2ApellidoDue;
    public javax.swing.JLabel lblBuscarNombreClientes;
    public javax.swing.JLabel lblCedulaDue;
    public javax.swing.JLabel lblDireccionDue;
    public javax.swing.JLabel lblEmailDue;
    public javax.swing.JLabel lblGeneroDue;
    public javax.swing.JLabel lblIdDuenofrm;
    public javax.swing.JLabel lblLogoDue;
    public static javax.swing.JLabel lblLogoDueno;
    public javax.swing.JLabel lblNombreDueno;
    public javax.swing.JLabel lblTelfDue;
    public javax.swing.JLabel lblTitleDuenos;
    public javax.swing.JPanel panelDetalleDue;
    public javax.swing.JPanel panelIngresarDatosDue;
    public javax.swing.JPanel panelMantMasc;
    public javax.swing.JTable tableDueno;
    public javax.swing.JTextField txt1ApellidoDue;
    public javax.swing.JTextField txt2ApellidoDue;
    public javax.swing.JTextField txtBuscarNombreDue;
    public javax.swing.JTextField txtCedulaDue;
    public javax.swing.JTextArea txtDireccionDue;
    public javax.swing.JTextField txtEmailDue;
    public javax.swing.JTextField txtIdDuenoFrm;
    public javax.swing.JTextField txtNombreDueno;
    public javax.swing.JTextField txtTelfDue;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
