/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControllerMascota;
import javax.swing.JOptionPane;

/**
 *
 * @author two_r
 */
public class frmMascota extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmMascota
     */
    public frmMascota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        panelMantMasc = new javax.swing.JPanel();
        lblTitleMascotas = new javax.swing.JLabel();
        panelDetalleMasc = new javax.swing.JPanel();
        lblBuscarNombreClientes = new javax.swing.JLabel();
        btnBuscarMasc = new javax.swing.JButton();
        txtBuscarNombreMasc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMascota = new javax.swing.JTable();
        btnEliminarMasc = new javax.swing.JButton();
        btnRefrescarMasc = new javax.swing.JButton();
        panelIngresarDatosMasc = new javax.swing.JPanel();
        lblIdMasc = new javax.swing.JLabel();
        lblNombreMasc = new javax.swing.JLabel();
        lblGeneroMasc = new javax.swing.JLabel();
        txtIdMasc = new javax.swing.JTextField();
        txtNombreMasc = new javax.swing.JTextField();
        lblTipoMasc = new javax.swing.JLabel();
        lblRazaMasc = new javax.swing.JLabel();
        btnCancelarMasc = new javax.swing.JButton();
        btnGuardarMasc = new javax.swing.JButton();
        btnEditarMasc = new javax.swing.JButton();
        cboxGeneroMasc = new javax.swing.JComboBox<>();
        cboxTipoMasc = new javax.swing.JComboBox<>();
        cboxRazaMasc = new javax.swing.JComboBox<>();
        lblActivoMasc = new javax.swing.JLabel();
        cboxActivoMasc = new javax.swing.JComboBox<>();
        lblIdDueno = new javax.swing.JLabel();
        txtIdDueno = new javax.swing.JTextField();
        lblNombreDueno = new javax.swing.JLabel();
        cbDueno = new javax.swing.JComboBox<>();
        lblLogoMasc = new javax.swing.JLabel();
        lblLogoMascota = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Ventana Mascotas");

        panelMantMasc.setBackground(new java.awt.Color(255, 255, 255));
        panelMantMasc.setForeground(new java.awt.Color(255, 255, 255));

        lblTitleMascotas.setFont(new java.awt.Font("SansSerif", 3, 22)); // NOI18N
        lblTitleMascotas.setText("MANTENIMIENTO DE MASCOTAS");

        panelDetalleMasc.setBackground(new java.awt.Color(255, 255, 255));
        panelDetalleMasc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12))); // NOI18N

        lblBuscarNombreClientes.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblBuscarNombreClientes.setText("Buscar por Nombre de Mascota:");

        btnBuscarMasc.setBackground(new java.awt.Color(255, 153, 0));
        btnBuscarMasc.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnBuscarMasc.setText("BUSCAR");
        btnBuscarMasc.setToolTipText("Busca por nombre la mascota");

        txtBuscarNombreMasc.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N

        tableMascota.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tableMascota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID DE MASCOTA", "NOMBRE", "GÉNERO", "TIPO ", "RAZA", "ACTIVO", "ID DE DUEÑO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableMascota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMascotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableMascota);
        if (tableMascota.getColumnModel().getColumnCount() > 0) {
            tableMascota.getColumnModel().getColumn(0).setResizable(false);
            tableMascota.getColumnModel().getColumn(1).setResizable(false);
            tableMascota.getColumnModel().getColumn(2).setResizable(false);
            tableMascota.getColumnModel().getColumn(3).setResizable(false);
            tableMascota.getColumnModel().getColumn(4).setResizable(false);
            tableMascota.getColumnModel().getColumn(5).setResizable(false);
            tableMascota.getColumnModel().getColumn(6).setResizable(false);
        }

        btnEliminarMasc.setBackground(new java.awt.Color(35, 61, 83));
        btnEliminarMasc.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnEliminarMasc.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarMasc.setText("ELIMINAR");
        btnEliminarMasc.setToolTipText("Elimina una mascota de la tabla");

        btnRefrescarMasc.setBackground(new java.awt.Color(6, 75, 115));
        btnRefrescarMasc.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnRefrescarMasc.setForeground(new java.awt.Color(255, 255, 255));
        btnRefrescarMasc.setText("REFRESCAR");
        btnRefrescarMasc.setToolTipText("Limpia los campos de la tabla");

        javax.swing.GroupLayout panelDetalleMascLayout = new javax.swing.GroupLayout(panelDetalleMasc);
        panelDetalleMasc.setLayout(panelDetalleMascLayout);
        panelDetalleMascLayout.setHorizontalGroup(
            panelDetalleMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetalleMascLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetalleMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                    .addGroup(panelDetalleMascLayout.createSequentialGroup()
                        .addComponent(lblBuscarNombreClientes)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarNombreMasc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarMasc))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetalleMascLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRefrescarMasc, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarMasc, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelDetalleMascLayout.setVerticalGroup(
            panelDetalleMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetalleMascLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetalleMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarNombreClientes)
                    .addComponent(btnBuscarMasc)
                    .addComponent(txtBuscarNombreMasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelDetalleMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefrescarMasc)
                    .addComponent(btnEliminarMasc))
                .addContainerGap())
        );

        panelIngresarDatosMasc.setBackground(new java.awt.Color(255, 255, 255));
        panelIngresarDatosMasc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingresar Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12))); // NOI18N
        panelIngresarDatosMasc.setToolTipText("Formulario para añadir una mascota");

        lblIdMasc.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblIdMasc.setText("ID de Mascota:");

        lblNombreMasc.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblNombreMasc.setText("Nombre de Mascota:");

        lblGeneroMasc.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblGeneroMasc.setText("Género de Mascota:");

        txtIdMasc.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N

        txtNombreMasc.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtNombreMasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreMascActionPerformed(evt);
            }
        });

        lblTipoMasc.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblTipoMasc.setText("Tipo de Mascota:");

        lblRazaMasc.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblRazaMasc.setText("Raza de Mascota:");

        btnCancelarMasc.setBackground(new java.awt.Color(35, 61, 83));
        btnCancelarMasc.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnCancelarMasc.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarMasc.setText("CANCELAR");
        btnCancelarMasc.setToolTipText("Cancela las acciones");

        btnGuardarMasc.setBackground(new java.awt.Color(255, 153, 0));
        btnGuardarMasc.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnGuardarMasc.setText("GUARDAR");
        btnGuardarMasc.setToolTipText("Guarda los cambios");

        btnEditarMasc.setBackground(new java.awt.Color(254, 189, 105));
        btnEditarMasc.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnEditarMasc.setText("EDITAR");
        btnEditarMasc.setToolTipText("Actualiza la información de la mascota");

        cboxGeneroMasc.setBackground(new java.awt.Color(102, 102, 102));
        cboxGeneroMasc.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        cboxGeneroMasc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Macho", "Hembra" }));

        cboxTipoMasc.setBackground(new java.awt.Color(102, 102, 102));
        cboxTipoMasc.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        cboxTipoMasc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perro", "Gato", "Hámster", "Pez", "Pájaro", " " }));

        cboxRazaMasc.setBackground(new java.awt.Color(102, 102, 102));
        cboxRazaMasc.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        cboxRazaMasc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perro Zaguate", "Gato Bengala", "Hámster Ruso", "Pez Guppy", "Pájaro de Amor", " " }));

        lblActivoMasc.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblActivoMasc.setText("Activo:");

        cboxActivoMasc.setBackground(new java.awt.Color(102, 102, 102));
        cboxActivoMasc.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        cboxActivoMasc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO" }));

        lblIdDueno.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblIdDueno.setText("Id de Dueño:");

        lblNombreDueno.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblNombreDueno.setText("Nombre Dueño:");

        cbDueno.setBackground(new java.awt.Color(102, 102, 102));
        cbDueno.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N

        javax.swing.GroupLayout panelIngresarDatosMascLayout = new javax.swing.GroupLayout(panelIngresarDatosMasc);
        panelIngresarDatosMasc.setLayout(panelIngresarDatosMascLayout);
        panelIngresarDatosMascLayout.setHorizontalGroup(
            panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarDatosMascLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIngresarDatosMascLayout.createSequentialGroup()
                        .addComponent(lblGeneroMasc)
                        .addGap(18, 18, 18)
                        .addComponent(cboxGeneroMasc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelIngresarDatosMascLayout.createSequentialGroup()
                        .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdMasc)
                            .addComponent(lblNombreMasc))
                        .addGap(18, 18, 18)
                        .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreMasc)
                            .addComponent(txtIdMasc)))
                    .addGroup(panelIngresarDatosMascLayout.createSequentialGroup()
                        .addComponent(lblTipoMasc)
                        .addGap(34, 34, 34)
                        .addComponent(cboxTipoMasc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelIngresarDatosMascLayout.createSequentialGroup()
                        .addComponent(lblRazaMasc)
                        .addGap(30, 30, 30)
                        .addComponent(cboxRazaMasc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelIngresarDatosMascLayout.createSequentialGroup()
                        .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblActivoMasc)
                            .addComponent(lblIdDueno))
                        .addGap(55, 55, 55)
                        .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboxActivoMasc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIdDueno)))
                    .addGroup(panelIngresarDatosMascLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnGuardarMasc, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarMasc, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarMasc, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelIngresarDatosMascLayout.createSequentialGroup()
                        .addComponent(lblNombreDueno)
                        .addGap(40, 40, 40)
                        .addComponent(cbDueno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelIngresarDatosMascLayout.setVerticalGroup(
            panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarDatosMascLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdMasc)
                    .addComponent(txtIdMasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreMasc)
                    .addComponent(txtNombreMasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxGeneroMasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGeneroMasc))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoMasc)
                    .addComponent(cboxTipoMasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRazaMasc)
                    .addComponent(cboxRazaMasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActivoMasc)
                    .addComponent(cboxActivoMasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdDueno)
                    .addComponent(txtIdDueno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreDueno)
                    .addComponent(cbDueno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarMasc)
                    .addComponent(btnEditarMasc)
                    .addComponent(btnCancelarMasc))
                .addContainerGap())
        );

        lblLogoMascota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rsz_2mimasc2.jpg"))); // NOI18N

        javax.swing.GroupLayout panelMantMascLayout = new javax.swing.GroupLayout(panelMantMasc);
        panelMantMasc.setLayout(panelMantMascLayout);
        panelMantMascLayout.setHorizontalGroup(
            panelMantMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMantMascLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMantMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelIngresarDatosMasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitleMascotas))
                .addGroup(panelMantMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMantMascLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelMantMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMantMascLayout.createSequentialGroup()
                                .addComponent(panelDetalleMasc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMantMascLayout.createSequentialGroup()
                                .addGap(0, 444, Short.MAX_VALUE)
                                .addComponent(lblLogoMasc)
                                .addGap(224, 224, 224))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMantMascLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLogoMascota)
                        .addGap(230, 230, 230))))
        );
        panelMantMascLayout.setVerticalGroup(
            panelMantMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMantMascLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMantMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelMantMascLayout.createSequentialGroup()
                        .addComponent(lblLogoMasc)
                        .addGap(12, 12, 12)
                        .addComponent(lblLogoMascota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelDetalleMasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMantMascLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTitleMascotas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelIngresarDatosMasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMantMasc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMantMasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMascotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMascotaMouseClicked
try{
        
            int fila = tableMascota.getSelectedRow();
            txtIdMasc.setText(tableMascota.getValueAt(fila, 0).toString());
            txtNombreMasc.setText(tableMascota.getValueAt(fila, 1).toString());
            cboxGeneroMasc.setSelectedItem(tableMascota.getValueAt(fila, 2));
            cboxTipoMasc.setSelectedItem(tableMascota.getValueAt(fila, 3));
            cboxRazaMasc.setSelectedItem(tableMascota.getValueAt(fila, 4));
            cboxActivoMasc.setSelectedItem(tableMascota.getValueAt(fila, 5));
            txtIdDueno.setText(tableMascota.getValueAt(fila, 6).toString()); 
           
            
        }catch (Exception e){
        
            JOptionPane.showMessageDialog(this, "ERROR AL SELECCIONAR UN REGISTRO:" + e.getMessage());
            
        }       
            
    }//GEN-LAST:event_tableMascotaMouseClicked

    private void txtNombreMascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreMascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMascActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              frmMascota mas = new frmMascota();
                ControllerMascota con = new ControllerMascota(mas);
                con.iniciar();
                mas.setVisible(true);
                mas.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarMasc;
    public javax.swing.JButton btnCancelarMasc;
    public javax.swing.JButton btnEditarMasc;
    public javax.swing.JButton btnEliminarMasc;
    public javax.swing.JButton btnGuardarMasc;
    public javax.swing.JButton btnRefrescarMasc;
    public javax.swing.JComboBox<String> cbDueno;
    public javax.swing.JComboBox<String> cboxActivoMasc;
    public javax.swing.JComboBox<String> cboxGeneroMasc;
    public javax.swing.JComboBox<String> cboxRazaMasc;
    public javax.swing.JComboBox<String> cboxTipoMasc;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblActivoMasc;
    public javax.swing.JLabel lblBuscarNombreClientes;
    public javax.swing.JLabel lblGeneroMasc;
    public javax.swing.JLabel lblIdDueno;
    public javax.swing.JLabel lblIdMasc;
    public javax.swing.JLabel lblLogoMasc;
    private javax.swing.JLabel lblLogoMascota;
    private javax.swing.JLabel lblNombreDueno;
    public javax.swing.JLabel lblNombreMasc;
    public javax.swing.JLabel lblRazaMasc;
    public javax.swing.JLabel lblTipoMasc;
    public javax.swing.JLabel lblTitleMascotas;
    public javax.swing.JPanel panelDetalleMasc;
    public javax.swing.JPanel panelIngresarDatosMasc;
    public javax.swing.JPanel panelMantMasc;
    public javax.swing.JTable tableMascota;
    public javax.swing.JTextField txtBuscarNombreMasc;
    public javax.swing.JTextField txtIdDueno;
    public javax.swing.JTextField txtIdMasc;
    public javax.swing.JTextField txtNombreMasc;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
