/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControllerMascota;
import controlador.ControllerReporteDueno;
import javax.swing.JOptionPane;

/**
 *
 * @author two_r
 */
public class frmReporteDueno extends javax.swing.JFrame {

    /**
     * Creates new form frmReporteDueno
     */
    public frmReporteDueno() {
        initComponents();
        setTitle("Reporte Por Dueño");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelReporteCita5 = new javax.swing.JPanel();
        lblTitleReporteDue = new javax.swing.JLabel();
        panelTablaReporteCita5 = new javax.swing.JPanel();
        lblCedReporteDueno = new javax.swing.JLabel();
        btnBuscarCedReporteDue = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableReporteDueno = new javax.swing.JTable();
        btnImprimirReporteDueno = new javax.swing.JButton();
        cboxCedReporteDue = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reporte Por Dueño");

        panelReporteCita5.setBackground(new java.awt.Color(255, 255, 255));

        lblTitleReporteDue.setFont(new java.awt.Font("SansSerif", 3, 22)); // NOI18N
        lblTitleReporteDue.setText("REPORTE DE CITAS POR DUEÑO");

        panelTablaReporteCita5.setBackground(new java.awt.Color(255, 255, 255));
        panelTablaReporteCita5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        lblCedReporteDueno.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblCedReporteDueno.setText("Seleccione una Cédula:");

        btnBuscarCedReporteDue.setBackground(new java.awt.Color(255, 153, 0));
        btnBuscarCedReporteDue.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnBuscarCedReporteDue.setText("BUSCAR");
        btnBuscarCedReporteDue.setToolTipText("Busca por cédula la cita registrada");

        tableReporteDueno.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tableReporteDueno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID DE CITA", "ASUNTO", "FECHA", "HORA", "FECHA DE CREACIÓN", "ID DE DUEÑO", "ID DE VET.", "ID DE USUARIO", "CÉDULA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableReporteDueno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableReporteDuenoMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tableReporteDueno);

        btnImprimirReporteDueno.setBackground(new java.awt.Color(6, 75, 115));
        btnImprimirReporteDueno.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnImprimirReporteDueno.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimirReporteDueno.setText("IMPRIMIR");
        btnImprimirReporteDueno.setToolTipText("Exporta la información de la tabla");

        cboxCedReporteDue.setBackground(new java.awt.Color(102, 102, 102));
        cboxCedReporteDue.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N

        javax.swing.GroupLayout panelTablaReporteCita5Layout = new javax.swing.GroupLayout(panelTablaReporteCita5);
        panelTablaReporteCita5.setLayout(panelTablaReporteCita5Layout);
        panelTablaReporteCita5Layout.setHorizontalGroup(
            panelTablaReporteCita5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaReporteCita5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTablaReporteCita5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnImprimirReporteDueno, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTablaReporteCita5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelTablaReporteCita5Layout.createSequentialGroup()
                            .addComponent(lblCedReporteDueno)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cboxCedReporteDue, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnBuscarCedReporteDue, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTablaReporteCita5Layout.setVerticalGroup(
            panelTablaReporteCita5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaReporteCita5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelTablaReporteCita5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedReporteDueno)
                    .addComponent(cboxCedReporteDue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCedReporteDue))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnImprimirReporteDueno)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelReporteCita5Layout = new javax.swing.GroupLayout(panelReporteCita5);
        panelReporteCita5.setLayout(panelReporteCita5Layout);
        panelReporteCita5Layout.setHorizontalGroup(
            panelReporteCita5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReporteCita5Layout.createSequentialGroup()
                .addGroup(panelReporteCita5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReporteCita5Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(lblTitleReporteDue))
                    .addGroup(panelReporteCita5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(panelTablaReporteCita5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelReporteCita5Layout.setVerticalGroup(
            panelReporteCita5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReporteCita5Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(lblTitleReporteDue)
                .addGap(18, 18, 18)
                .addComponent(panelTablaReporteCita5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelReporteCita5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelReporteCita5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tableReporteDuenoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableReporteDuenoMouseClicked
  
            
    }//GEN-LAST:event_tableReporteDuenoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReporteDueno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReporteDueno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReporteDueno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReporteDueno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmReporteDueno due = new frmReporteDueno();
                 ControllerReporteDueno con = new ControllerReporteDueno(due);
                con.iniciar();
                due.setVisible(true);
                due.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarCedReporteDue;
    public javax.swing.JButton btnImprimirReporteDueno;
    public javax.swing.JComboBox<String> cboxCedReporteDue;
    private javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JLabel lblCedReporteDueno;
    public javax.swing.JLabel lblTitleReporteDue;
    private javax.swing.JPanel panelReporteCita5;
    private javax.swing.JPanel panelTablaReporteCita5;
    public javax.swing.JTable tableReporteDueno;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
