/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author two_r
 */
public class frmReporteFecha extends javax.swing.JFrame {

    /**
     * Creates new form frmReporteCita
     */
    public frmReporteFecha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelReporteFecha = new javax.swing.JPanel();
        lblTitleReporteFecha = new javax.swing.JLabel();
        panelTablaReporteFecha = new javax.swing.JPanel();
        lblFechaReporteFecha = new javax.swing.JLabel();
        fechaReporteFecha = new com.toedter.calendar.JDateChooser();
        btnBuscarReporteFecha = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReporteFecha = new javax.swing.JTable();
        btnImprimirReporteFecha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reporte por Fechas");
        setResizable(false);

        panelReporteFecha.setBackground(new java.awt.Color(255, 255, 255));

        lblTitleReporteFecha.setFont(new java.awt.Font("SansSerif", 3, 22)); // NOI18N
        lblTitleReporteFecha.setText("REPORTE DE CITAS POR FECHAS");

        panelTablaReporteFecha.setBackground(new java.awt.Color(255, 255, 255));
        panelTablaReporteFecha.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        lblFechaReporteFecha.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblFechaReporteFecha.setText("Seleccione una Fecha:");

        btnBuscarReporteFecha.setBackground(new java.awt.Color(255, 153, 0));
        btnBuscarReporteFecha.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnBuscarReporteFecha.setText("BUSCAR");
        btnBuscarReporteFecha.setToolTipText("Busca por fecha la cita registrada");

        tableReporteFecha.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tableReporteFecha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID DE CITA", "ASUNTO", "FECHA", "HORA", "FECHA DE CREACIÓN", "ID DE DUEÑO", "ID DE VET.", "ID DE USUARIO", "CÉDULA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableReporteFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableReporteFechaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableReporteFecha);

        btnImprimirReporteFecha.setBackground(new java.awt.Color(6, 75, 115));
        btnImprimirReporteFecha.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnImprimirReporteFecha.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimirReporteFecha.setText("IMPRIMIR");
        btnImprimirReporteFecha.setToolTipText("Exporta la información de la tabla");

        javax.swing.GroupLayout panelTablaReporteFechaLayout = new javax.swing.GroupLayout(panelTablaReporteFecha);
        panelTablaReporteFecha.setLayout(panelTablaReporteFechaLayout);
        panelTablaReporteFechaLayout.setHorizontalGroup(
            panelTablaReporteFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaReporteFechaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTablaReporteFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelTablaReporteFechaLayout.createSequentialGroup()
                        .addComponent(lblFechaReporteFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fechaReporteFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarReporteFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTablaReporteFechaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnImprimirReporteFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelTablaReporteFechaLayout.setVerticalGroup(
            panelTablaReporteFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaReporteFechaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelTablaReporteFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscarReporteFecha)
                    .addGroup(panelTablaReporteFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblFechaReporteFecha)
                        .addComponent(fechaReporteFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnImprimirReporteFecha)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelReporteFechaLayout = new javax.swing.GroupLayout(panelReporteFecha);
        panelReporteFecha.setLayout(panelReporteFechaLayout);
        panelReporteFechaLayout.setHorizontalGroup(
            panelReporteFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReporteFechaLayout.createSequentialGroup()
                .addGroup(panelReporteFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReporteFechaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(panelTablaReporteFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelReporteFechaLayout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(lblTitleReporteFecha)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelReporteFechaLayout.setVerticalGroup(
            panelReporteFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReporteFechaLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(lblTitleReporteFecha)
                .addGap(18, 18, 18)
                .addComponent(panelTablaReporteFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelReporteFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelReporteFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tableReporteFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableReporteFechaMouseClicked

    
    }//GEN-LAST:event_tableReporteFechaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReporteFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReporteFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReporteFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReporteFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarReporteFecha;
    public javax.swing.JButton btnImprimirReporteFecha;
    public com.toedter.calendar.JDateChooser fechaReporteFecha;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblFechaReporteFecha;
    public javax.swing.JLabel lblTitleReporteFecha;
    public javax.swing.JPanel panelReporteFecha;
    public javax.swing.JPanel panelTablaReporteFecha;
    public javax.swing.JTable tableReporteFecha;
    // End of variables declaration//GEN-END:variables
}
