/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControllerUsuario;
import javax.swing.JOptionPane;

/**
 *
 * @author two_r
 */
public class frmUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmUsuario
     */
    public frmUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMantMasc = new javax.swing.JPanel();
        lblTitleClientes = new javax.swing.JLabel();
        panelDetalleUser = new javax.swing.JPanel();
        lblBuscarNombreUser = new javax.swing.JLabel();
        btnBuscarUser = new javax.swing.JButton();
        txtBuscarNombreUser = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUser = new javax.swing.JTable();
        btnEliminarUser = new javax.swing.JButton();
        btnRefrescarUser = new javax.swing.JButton();
        panelIngresarDatosUser = new javax.swing.JPanel();
        lblIdUserFrm = new javax.swing.JLabel();
        lblNombreUser = new javax.swing.JLabel();
        lbl1ApellidoUser = new javax.swing.JLabel();
        txtIdUserFrm = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        lbl2ApellidoUser = new javax.swing.JLabel();
        lblEmailUser = new javax.swing.JLabel();
        btnCancelarUser = new javax.swing.JButton();
        btnGuardarUser = new javax.swing.JButton();
        btnEditarUser = new javax.swing.JButton();
        lblNombreUserFrm = new javax.swing.JLabel();
        cboxTipoUserFrm = new javax.swing.JComboBox<>();
        lblPasswordUser = new javax.swing.JLabel();
        lblTipoUserFrm = new javax.swing.JLabel();
        txt1ApellidoUser = new javax.swing.JTextField();
        txt2ApellidoUser = new javax.swing.JTextField();
        txtEmailUser = new javax.swing.JTextField();
        txtNombreUsuario = new javax.swing.JTextField();
        lblActivo = new javax.swing.JLabel();
        cboxActivo = new javax.swing.JComboBox<>();
        txtPasswordUser = new javax.swing.JPasswordField();
        lblLogoUser = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Ventana Usuarios");

        panelMantMasc.setBackground(new java.awt.Color(255, 255, 255));
        panelMantMasc.setForeground(new java.awt.Color(255, 255, 255));

        lblTitleClientes.setFont(new java.awt.Font("SansSerif", 3, 22)); // NOI18N
        lblTitleClientes.setText("MANTENIMIENTO DE USUARIOS");

        panelDetalleUser.setBackground(new java.awt.Color(255, 255, 255));
        panelDetalleUser.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12))); // NOI18N

        lblBuscarNombreUser.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblBuscarNombreUser.setText("Buscar por Nombre:");

        btnBuscarUser.setBackground(new java.awt.Color(255, 153, 0));
        btnBuscarUser.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnBuscarUser.setText("BUSCAR");
        btnBuscarUser.setToolTipText("Buscar por nombre el usuario");

        txtBuscarNombreUser.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtBuscarNombreUser.setToolTipText("Ingrese un nombre para buscar y filtrar la tabla");

        tableUser.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID DE USUARIO", "NOMBRE", "PRIMER APELLIDO", "SEGUNDO APELLIDO", "E-MAIL", "USUARIO", "CONTRASEÑA", "TIPO DE USUARIO", "ACTIVO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableUser);
        if (tableUser.getColumnModel().getColumnCount() > 0) {
            tableUser.getColumnModel().getColumn(0).setResizable(false);
            tableUser.getColumnModel().getColumn(1).setResizable(false);
            tableUser.getColumnModel().getColumn(2).setResizable(false);
            tableUser.getColumnModel().getColumn(3).setResizable(false);
            tableUser.getColumnModel().getColumn(4).setResizable(false);
            tableUser.getColumnModel().getColumn(5).setResizable(false);
            tableUser.getColumnModel().getColumn(6).setResizable(false);
            tableUser.getColumnModel().getColumn(7).setResizable(false);
            tableUser.getColumnModel().getColumn(8).setResizable(false);
        }

        btnEliminarUser.setBackground(new java.awt.Color(35, 61, 83));
        btnEliminarUser.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnEliminarUser.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarUser.setText("ELIMINAR");
        btnEliminarUser.setToolTipText("Elimina un usuario de la tabla");

        btnRefrescarUser.setBackground(new java.awt.Color(6, 75, 115));
        btnRefrescarUser.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnRefrescarUser.setForeground(new java.awt.Color(255, 255, 255));
        btnRefrescarUser.setText("REFRESCAR");
        btnRefrescarUser.setToolTipText("Refresca los usuarios de la tabla");

        javax.swing.GroupLayout panelDetalleUserLayout = new javax.swing.GroupLayout(panelDetalleUser);
        panelDetalleUser.setLayout(panelDetalleUserLayout);
        panelDetalleUserLayout.setHorizontalGroup(
            panelDetalleUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetalleUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetalleUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                    .addGroup(panelDetalleUserLayout.createSequentialGroup()
                        .addComponent(lblBuscarNombreUser)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarNombreUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarUser))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetalleUserLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRefrescarUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarUser)))
                .addContainerGap())
        );
        panelDetalleUserLayout.setVerticalGroup(
            panelDetalleUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetalleUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetalleUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarNombreUser)
                    .addComponent(btnBuscarUser)
                    .addComponent(txtBuscarNombreUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelDetalleUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefrescarUser)
                    .addComponent(btnEliminarUser))
                .addContainerGap())
        );

        panelIngresarDatosUser.setBackground(new java.awt.Color(255, 255, 255));
        panelIngresarDatosUser.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingresar Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12))); // NOI18N

        lblIdUserFrm.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblIdUserFrm.setText("ID de Usuario:");

        lblNombreUser.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblNombreUser.setText("Nombre:");

        lbl1ApellidoUser.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lbl1ApellidoUser.setText("Primer Apellido:");

        txtIdUserFrm.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N

        txtNombre.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        lbl2ApellidoUser.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lbl2ApellidoUser.setText("Segundo Apellido:");

        lblEmailUser.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblEmailUser.setText("E-mail:");

        btnCancelarUser.setBackground(new java.awt.Color(35, 61, 83));
        btnCancelarUser.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnCancelarUser.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarUser.setText("CANCELAR");
        btnCancelarUser.setToolTipText("Cancelan todas las acciones");

        btnGuardarUser.setBackground(new java.awt.Color(255, 153, 0));
        btnGuardarUser.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnGuardarUser.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarUser.setText("GUARDAR");
        btnGuardarUser.setToolTipText("Guardar los cambios de usuario");

        btnEditarUser.setBackground(new java.awt.Color(254, 189, 105));
        btnEditarUser.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnEditarUser.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarUser.setText("EDITAR");
        btnEditarUser.setToolTipText("Actualiza el usuario existente");

        lblNombreUserFrm.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblNombreUserFrm.setText("Nombre de Usuario:");

        cboxTipoUserFrm.setBackground(new java.awt.Color(102, 102, 102));
        cboxTipoUserFrm.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        cboxTipoUserFrm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Asistente" }));

        lblPasswordUser.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblPasswordUser.setText("Contraseña:");

        lblTipoUserFrm.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblTipoUserFrm.setText("Tipo de Usuario:");

        txt1ApellidoUser.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txt1ApellidoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ApellidoUserActionPerformed(evt);
            }
        });

        txt2ApellidoUser.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txt2ApellidoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ApellidoUserActionPerformed(evt);
            }
        });

        txtEmailUser.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtEmailUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailUserActionPerformed(evt);
            }
        });

        txtNombreUsuario.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioActionPerformed(evt);
            }
        });

        lblActivo.setText("Activo:");

        cboxActivo.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        cboxActivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));

        txtPasswordUser.setText("jPasswordField1");

        javax.swing.GroupLayout panelIngresarDatosUserLayout = new javax.swing.GroupLayout(panelIngresarDatosUser);
        panelIngresarDatosUser.setLayout(panelIngresarDatosUserLayout);
        panelIngresarDatosUserLayout.setHorizontalGroup(
            panelIngresarDatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarDatosUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIngresarDatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIngresarDatosUserLayout.createSequentialGroup()
                        .addGroup(panelIngresarDatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdUserFrm)
                            .addComponent(lblNombreUser))
                        .addGap(59, 59, 59)
                        .addGroup(panelIngresarDatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre)
                            .addComponent(txtIdUserFrm)))
                    .addGroup(panelIngresarDatosUserLayout.createSequentialGroup()
                        .addGroup(panelIngresarDatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl2ApellidoUser)
                            .addComponent(lbl1ApellidoUser))
                        .addGap(39, 39, 39)
                        .addGroup(panelIngresarDatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt2ApellidoUser)
                            .addComponent(txt1ApellidoUser)))
                    .addGroup(panelIngresarDatosUserLayout.createSequentialGroup()
                        .addGroup(panelIngresarDatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreUserFrm)
                            .addComponent(lblPasswordUser)
                            .addComponent(lblEmailUser))
                        .addGap(31, 31, 31)
                        .addGroup(panelIngresarDatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreUsuario)
                            .addComponent(txtEmailUser)
                            .addComponent(txtPasswordUser)))
                    .addGroup(panelIngresarDatosUserLayout.createSequentialGroup()
                        .addComponent(lblTipoUserFrm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboxTipoUserFrm, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelIngresarDatosUserLayout.createSequentialGroup()
                        .addComponent(lblActivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboxActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(panelIngresarDatosUserLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnGuardarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelIngresarDatosUserLayout.setVerticalGroup(
            panelIngresarDatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarDatosUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIngresarDatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdUserFrm)
                    .addComponent(txtIdUserFrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelIngresarDatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreUser)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1ApellidoUser)
                    .addComponent(txt1ApellidoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2ApellidoUser)
                    .addComponent(txt2ApellidoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailUser)
                    .addComponent(txtEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelIngresarDatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreUserFrm)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPasswordUser)
                    .addComponent(txtPasswordUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoUserFrm)
                    .addComponent(cboxTipoUserFrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblActivo)
                    .addComponent(cboxActivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(panelIngresarDatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarUser)
                    .addComponent(btnEditarUser)
                    .addComponent(btnCancelarUser))
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout panelMantMascLayout = new javax.swing.GroupLayout(panelMantMasc);
        panelMantMasc.setLayout(panelMantMascLayout);
        panelMantMascLayout.setHorizontalGroup(
            panelMantMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMantMascLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMantMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMantMascLayout.createSequentialGroup()
                        .addComponent(lblTitleClientes)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelIngresarDatosUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panelMantMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMantMascLayout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(lblLogoUser))
                    .addGroup(panelMantMascLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelDetalleUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelMantMascLayout.setVerticalGroup(
            panelMantMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMantMascLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMantMascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMantMascLayout.createSequentialGroup()
                        .addComponent(lblLogoUser)
                        .addGap(18, 18, 18)
                        .addComponent(panelDetalleUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(panelMantMascLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTitleClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelIngresarDatosUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMantMasc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMantMasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUserMouseClicked
      try{
        
            int fila = tableUser.getSelectedRow();
            txtIdUserFrm.setText(tableUser.getValueAt(fila, 0).toString());
            txtNombre.setText(tableUser.getValueAt(fila, 1).toString());
            txt1ApellidoUser.setText(tableUser.getValueAt(fila, 2).toString());
            txt2ApellidoUser.setText(tableUser.getValueAt(fila, 3).toString());
            txtEmailUser.setText(tableUser.getValueAt(fila, 4).toString());
            txtNombreUsuario.setText(tableUser.getValueAt(fila, 5).toString());
            txtPasswordUser.setText(tableUser.getValueAt(fila, 6).toString());
            cboxTipoUserFrm.setSelectedItem(tableUser.getValueAt(fila, 7));
            cboxActivo.setSelectedItem(tableUser.getValueAt(fila, 8));
            
        }catch (Exception e){
        
            JOptionPane.showMessageDialog(this, "ERROR AL SELECCIONAR UN REGISTRO:" + e.getMessage());
            
        }       
    }//GEN-LAST:event_tableUserMouseClicked

    private void txtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioActionPerformed

    private void txtEmailUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailUserActionPerformed

    private void txt2ApellidoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ApellidoUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2ApellidoUserActionPerformed

    private void txt1ApellidoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ApellidoUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ApellidoUserActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                frmUsuario user = new frmUsuario();
                ControllerUsuario con = new ControllerUsuario(user);
                con.iniciar();
                user.setVisible(true);
                user.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarUser;
    public javax.swing.JButton btnCancelarUser;
    public javax.swing.JButton btnEditarUser;
    public javax.swing.JButton btnEliminarUser;
    public javax.swing.JButton btnGuardarUser;
    public javax.swing.JButton btnRefrescarUser;
    public javax.swing.JComboBox<String> cboxActivo;
    public javax.swing.JComboBox<String> cboxTipoUserFrm;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lbl1ApellidoUser;
    public javax.swing.JLabel lbl2ApellidoUser;
    private javax.swing.JLabel lblActivo;
    public javax.swing.JLabel lblBuscarNombreUser;
    public javax.swing.JLabel lblEmailUser;
    public javax.swing.JLabel lblIdUserFrm;
    public javax.swing.JLabel lblLogoUser;
    public javax.swing.JLabel lblNombreUser;
    public javax.swing.JLabel lblNombreUserFrm;
    public javax.swing.JLabel lblPasswordUser;
    public javax.swing.JLabel lblTipoUserFrm;
    public javax.swing.JLabel lblTitleClientes;
    public javax.swing.JPanel panelDetalleUser;
    public javax.swing.JPanel panelIngresarDatosUser;
    public javax.swing.JPanel panelMantMasc;
    public javax.swing.JTable tableUser;
    public javax.swing.JTextField txt1ApellidoUser;
    public javax.swing.JTextField txt2ApellidoUser;
    public javax.swing.JTextField txtBuscarNombreUser;
    public javax.swing.JTextField txtEmailUser;
    public javax.swing.JTextField txtIdUserFrm;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtNombreUsuario;
    public javax.swing.JPasswordField txtPasswordUser;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
