/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControllerDueno;
import controlador.ControllerVeterinario;
import javax.swing.JOptionPane;

/**
 *
 * @author two_r
 */
public class frmVeterinario extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmVeterinario
     */
    public frmVeterinario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInservibleVet = new javax.swing.JPanel();
        panelMantVet = new javax.swing.JPanel();
        lblTitleVeterinarios = new javax.swing.JLabel();
        panelDetalleVet = new javax.swing.JPanel();
        lblBuscarNombreVet = new javax.swing.JLabel();
        btnBuscarVet = new javax.swing.JButton();
        txtBuscarNombreVet = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVet = new javax.swing.JTable();
        btnEliminarVet = new javax.swing.JButton();
        btnRefrescarVet = new javax.swing.JButton();
        panelIngresarDatosVet = new javax.swing.JPanel();
        lblIdVetFrm = new javax.swing.JLabel();
        lblNombreVetFrm = new javax.swing.JLabel();
        lbl1ApellidoVetFrm = new javax.swing.JLabel();
        txtIdVetFrm = new javax.swing.JTextField();
        txtNombreVetFrm = new javax.swing.JTextField();
        lbl2ApellidoVetFrm = new javax.swing.JLabel();
        lblCedulaVetFrm = new javax.swing.JLabel();
        btnCancelarVet = new javax.swing.JButton();
        btnGuardarVet = new javax.swing.JButton();
        btnEditarVet = new javax.swing.JButton();
        lblCodProfVetFrm = new javax.swing.JLabel();
        lblEmailVetFrm = new javax.swing.JLabel();
        txtEmailVetFrm = new javax.swing.JTextField();
        txt1ApellidoVetFrm = new javax.swing.JTextField();
        txt2ApellidoVetFrm = new javax.swing.JTextField();
        txtCedulaVetFrm = new javax.swing.JTextField();
        lblTelfVetFrm = new javax.swing.JLabel();
        txtTelfVetFrm = new javax.swing.JTextField();
        lblDireccionVetFrm = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDireccionVetFrm = new javax.swing.JTextArea();
        txtCodProfVetFrm = new javax.swing.JTextField();
        lblActivoVetFrm = new javax.swing.JLabel();
        cboxActivoVetFrm = new javax.swing.JComboBox<>();
        lblLogoVet = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Ventana Veterinarios");

        panelInservibleVet.setBackground(new java.awt.Color(255, 255, 255));

        panelMantVet.setBackground(new java.awt.Color(255, 255, 255));
        panelMantVet.setForeground(new java.awt.Color(255, 255, 255));

        lblTitleVeterinarios.setFont(new java.awt.Font("SansSerif", 3, 22)); // NOI18N
        lblTitleVeterinarios.setText("MANTENIMIENTO DE VETERINARIOS");

        panelDetalleVet.setBackground(new java.awt.Color(255, 255, 255));
        panelDetalleVet.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12))); // NOI18N

        lblBuscarNombreVet.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblBuscarNombreVet.setText("Buscar por Nombre:");

        btnBuscarVet.setBackground(new java.awt.Color(255, 153, 0));
        btnBuscarVet.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnBuscarVet.setText("BUSCAR");
        btnBuscarVet.setToolTipText("Busca por nombre el veterinario");

        txtBuscarNombreVet.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N

        tableVet.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tableVet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID DE VET.", "NOMBRE", "PRIMER APELLIDO", "SEGUNDO APELLIDO", "CÉDULA", "CÓDIGO PROFESIONAL", "E-MAIL", "TELÉFONO", "DIRECCIÓN", "ACTIVO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableVet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableVetMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableVet);
        if (tableVet.getColumnModel().getColumnCount() > 0) {
            tableVet.getColumnModel().getColumn(0).setResizable(false);
            tableVet.getColumnModel().getColumn(1).setResizable(false);
            tableVet.getColumnModel().getColumn(2).setResizable(false);
            tableVet.getColumnModel().getColumn(3).setResizable(false);
            tableVet.getColumnModel().getColumn(4).setResizable(false);
            tableVet.getColumnModel().getColumn(5).setResizable(false);
            tableVet.getColumnModel().getColumn(6).setResizable(false);
            tableVet.getColumnModel().getColumn(7).setResizable(false);
            tableVet.getColumnModel().getColumn(8).setResizable(false);
            tableVet.getColumnModel().getColumn(9).setResizable(false);
        }

        btnEliminarVet.setBackground(new java.awt.Color(35, 61, 83));
        btnEliminarVet.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnEliminarVet.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarVet.setText("ELIMINAR");
        btnEliminarVet.setToolTipText("Elimina un veterinario de la tabla");

        btnRefrescarVet.setBackground(new java.awt.Color(6, 75, 115));
        btnRefrescarVet.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnRefrescarVet.setForeground(new java.awt.Color(255, 255, 255));
        btnRefrescarVet.setText("REFRESCAR");
        btnRefrescarVet.setToolTipText("Limpia la tabla de los veterinarios");

        javax.swing.GroupLayout panelDetalleVetLayout = new javax.swing.GroupLayout(panelDetalleVet);
        panelDetalleVet.setLayout(panelDetalleVetLayout);
        panelDetalleVetLayout.setHorizontalGroup(
            panelDetalleVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetalleVetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetalleVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetalleVetLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRefrescarVet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarVet))
                    .addGroup(panelDetalleVetLayout.createSequentialGroup()
                        .addGroup(panelDetalleVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDetalleVetLayout.createSequentialGroup()
                                .addComponent(lblBuscarNombreVet)
                                .addGap(18, 18, 18)
                                .addComponent(txtBuscarNombreVet, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarVet, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDetalleVetLayout.setVerticalGroup(
            panelDetalleVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetalleVetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetalleVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarNombreVet)
                    .addComponent(btnBuscarVet)
                    .addComponent(txtBuscarNombreVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelDetalleVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefrescarVet)
                    .addComponent(btnEliminarVet))
                .addContainerGap())
        );

        panelIngresarDatosVet.setBackground(new java.awt.Color(255, 255, 255));
        panelIngresarDatosVet.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingresar Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12))); // NOI18N

        lblIdVetFrm.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblIdVetFrm.setText("ID de Veterinario:");

        lblNombreVetFrm.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblNombreVetFrm.setText("Nombre:");

        lbl1ApellidoVetFrm.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lbl1ApellidoVetFrm.setText("Primer Apellido:");

        txtIdVetFrm.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtIdVetFrm.setToolTipText("Ingresar ID del Veterinario");

        txtNombreVetFrm.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtNombreVetFrm.setToolTipText("Ingrese su Nombre ");
        txtNombreVetFrm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreVetFrmActionPerformed(evt);
            }
        });

        lbl2ApellidoVetFrm.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lbl2ApellidoVetFrm.setText("Segundo Apellido:");

        lblCedulaVetFrm.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblCedulaVetFrm.setText("Cédula:");

        btnCancelarVet.setBackground(new java.awt.Color(35, 61, 83));
        btnCancelarVet.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnCancelarVet.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarVet.setText("CANCELAR");
        btnCancelarVet.setToolTipText("Cancela todas las acciones");

        btnGuardarVet.setBackground(new java.awt.Color(255, 153, 0));
        btnGuardarVet.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnGuardarVet.setText("GUARDAR");
        btnGuardarVet.setToolTipText("Guarda la nueva información de los veterinarios");

        btnEditarVet.setBackground(new java.awt.Color(254, 189, 105));
        btnEditarVet.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnEditarVet.setText("EDITAR");
        btnEditarVet.setToolTipText("Actualiza un veterinario existente");

        lblCodProfVetFrm.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblCodProfVetFrm.setText("Código Profesional:");

        lblEmailVetFrm.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblEmailVetFrm.setText("E-mail:");

        txtEmailVetFrm.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtEmailVetFrm.setToolTipText("Ingrese su e-mail");
        txtEmailVetFrm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailVetFrmActionPerformed(evt);
            }
        });

        txt1ApellidoVetFrm.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txt1ApellidoVetFrm.setToolTipText("Ingrese su Primer Apellido");
        txt1ApellidoVetFrm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ApellidoVetFrmActionPerformed(evt);
            }
        });

        txt2ApellidoVetFrm.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txt2ApellidoVetFrm.setToolTipText("Ingrese su Segundo Apellido");
        txt2ApellidoVetFrm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ApellidoVetFrmActionPerformed(evt);
            }
        });

        txtCedulaVetFrm.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtCedulaVetFrm.setToolTipText("Ingrese su Cedula");
        txtCedulaVetFrm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaVetFrmActionPerformed(evt);
            }
        });

        lblTelfVetFrm.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblTelfVetFrm.setText("Teléfono:");

        txtTelfVetFrm.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtTelfVetFrm.setToolTipText("Ingrese su telefono");
        txtTelfVetFrm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelfVetFrmActionPerformed(evt);
            }
        });

        lblDireccionVetFrm.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblDireccionVetFrm.setText("Dirección:");

        txtDireccionVetFrm.setColumns(20);
        txtDireccionVetFrm.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtDireccionVetFrm.setRows(5);
        txtDireccionVetFrm.setToolTipText("Ingrese su direccion");
        txtDireccionVetFrm.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtDireccionVetFrm);

        txtCodProfVetFrm.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtCodProfVetFrm.setToolTipText("Ingrese su codigo profesional");
        txtCodProfVetFrm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodProfVetFrmActionPerformed(evt);
            }
        });

        lblActivoVetFrm.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblActivoVetFrm.setText("Activo:");

        cboxActivoVetFrm.setBackground(new java.awt.Color(102, 102, 102));
        cboxActivoVetFrm.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        cboxActivoVetFrm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));

        javax.swing.GroupLayout panelIngresarDatosVetLayout = new javax.swing.GroupLayout(panelIngresarDatosVet);
        panelIngresarDatosVet.setLayout(panelIngresarDatosVetLayout);
        panelIngresarDatosVetLayout.setHorizontalGroup(
            panelIngresarDatosVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarDatosVetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIngresarDatosVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIngresarDatosVetLayout.createSequentialGroup()
                        .addGroup(panelIngresarDatosVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdVetFrm)
                            .addComponent(lblNombreVetFrm))
                        .addGap(28, 28, 28)
                        .addGroup(panelIngresarDatosVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreVetFrm)
                            .addComponent(txtIdVetFrm)))
                    .addGroup(panelIngresarDatosVetLayout.createSequentialGroup()
                        .addGroup(panelIngresarDatosVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl1ApellidoVetFrm)
                            .addComponent(lbl2ApellidoVetFrm))
                        .addGap(24, 24, 24)
                        .addGroup(panelIngresarDatosVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt1ApellidoVetFrm)
                            .addComponent(txt2ApellidoVetFrm)))
                    .addGroup(panelIngresarDatosVetLayout.createSequentialGroup()
                        .addComponent(lblActivoVetFrm)
                        .addGap(59, 59, 59)
                        .addComponent(cboxActivoVetFrm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelIngresarDatosVetLayout.createSequentialGroup()
                        .addGroup(panelIngresarDatosVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCedulaVetFrm)
                            .addComponent(lblCodProfVetFrm))
                        .addGap(18, 18, 18)
                        .addGroup(panelIngresarDatosVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCedulaVetFrm)
                            .addComponent(txtCodProfVetFrm)))
                    .addGroup(panelIngresarDatosVetLayout.createSequentialGroup()
                        .addComponent(lblEmailVetFrm)
                        .addGap(80, 80, 80)
                        .addComponent(txtEmailVetFrm))
                    .addGroup(panelIngresarDatosVetLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnGuardarVet, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarVet, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarVet, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelIngresarDatosVetLayout.createSequentialGroup()
                        .addGroup(panelIngresarDatosVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelfVetFrm)
                            .addComponent(lblDireccionVetFrm))
                        .addGroup(panelIngresarDatosVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelIngresarDatosVetLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jScrollPane2))
                            .addGroup(panelIngresarDatosVetLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(txtTelfVetFrm)))))
                .addContainerGap())
        );
        panelIngresarDatosVetLayout.setVerticalGroup(
            panelIngresarDatosVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarDatosVetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIngresarDatosVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdVetFrm)
                    .addComponent(txtIdVetFrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelIngresarDatosVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreVetFrm)
                    .addComponent(txtNombreVetFrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1ApellidoVetFrm)
                    .addComponent(txt1ApellidoVetFrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2ApellidoVetFrm)
                    .addComponent(txt2ApellidoVetFrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedulaVetFrm)
                    .addComponent(txtCedulaVetFrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelIngresarDatosVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodProfVetFrm)
                    .addComponent(txtCodProfVetFrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailVetFrm)
                    .addComponent(txtEmailVetFrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelIngresarDatosVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelfVetFrm)
                    .addComponent(txtTelfVetFrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDireccionVetFrm)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxActivoVetFrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblActivoVetFrm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(panelIngresarDatosVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarVet)
                    .addComponent(btnEditarVet)
                    .addComponent(btnCancelarVet))
                .addContainerGap())
        );

        lblLogoVet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rsz_2mimasc2.jpg"))); // NOI18N

        javax.swing.GroupLayout panelMantVetLayout = new javax.swing.GroupLayout(panelMantVet);
        panelMantVet.setLayout(panelMantVetLayout);
        panelMantVetLayout.setHorizontalGroup(
            panelMantVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMantVetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMantVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelIngresarDatosVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitleVeterinarios))
                .addGroup(panelMantVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMantVetLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelDetalleVet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMantVetLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLogoVet)
                        .addGap(316, 316, 316))))
        );
        panelMantVetLayout.setVerticalGroup(
            panelMantVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMantVetLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(lblTitleVeterinarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMantVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelMantVetLayout.createSequentialGroup()
                        .addComponent(lblLogoVet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(panelDetalleVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelIngresarDatosVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelInservibleVetLayout = new javax.swing.GroupLayout(panelInservibleVet);
        panelInservibleVet.setLayout(panelInservibleVetLayout);
        panelInservibleVetLayout.setHorizontalGroup(
            panelInservibleVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMantVet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelInservibleVetLayout.setVerticalGroup(
            panelInservibleVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMantVet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInservibleVet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInservibleVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodProfVetFrmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodProfVetFrmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodProfVetFrmActionPerformed

    private void txtTelfVetFrmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelfVetFrmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelfVetFrmActionPerformed

    private void txtCedulaVetFrmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaVetFrmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaVetFrmActionPerformed

    private void txt2ApellidoVetFrmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ApellidoVetFrmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2ApellidoVetFrmActionPerformed

    private void txt1ApellidoVetFrmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ApellidoVetFrmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ApellidoVetFrmActionPerformed

    private void txtEmailVetFrmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailVetFrmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailVetFrmActionPerformed

    private void txtNombreVetFrmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreVetFrmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreVetFrmActionPerformed

    private void tableVetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableVetMouseClicked
  try{
        
            int fila = tableVet.getSelectedRow();
            txtIdVetFrm.setText(tableVet.getValueAt(fila, 0).toString());
            txtNombreVetFrm.setText(tableVet.getValueAt(fila, 1).toString());
            txt1ApellidoVetFrm.setText(tableVet.getValueAt(fila, 2).toString());
            txt2ApellidoVetFrm.setText(tableVet.getValueAt(fila, 3).toString());
            txtCedulaVetFrm.setText(tableVet.getValueAt(fila, 4).toString());
            txtCodProfVetFrm.setText(tableVet.getValueAt(fila, 5).toString());
            txtEmailVetFrm.setText(tableVet.getValueAt(fila, 6).toString());
            txtTelfVetFrm.setText(tableVet.getValueAt(fila, 7).toString());
            txtDireccionVetFrm.setText(tableVet.getValueAt(fila, 8).toString());
            cboxActivoVetFrm.setSelectedItem(tableVet.getValueAt(fila,9));
            
            
        }catch (Exception e){
        
            JOptionPane.showMessageDialog(this, "ERROR AL SELECCIONAR UN REGISTRO:" + e.getMessage());
            
        } 
    }//GEN-LAST:event_tableVetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmVeterinario vete = new frmVeterinario();
                ControllerVeterinario con = new ControllerVeterinario(vete);
                con.iniciar();
                vete.setVisible(true);
                vete.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarVet;
    public javax.swing.JButton btnCancelarVet;
    public javax.swing.JButton btnEditarVet;
    public javax.swing.JButton btnEliminarVet;
    public javax.swing.JButton btnGuardarVet;
    public javax.swing.JButton btnRefrescarVet;
    public javax.swing.JComboBox<String> cboxActivoVetFrm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lbl1ApellidoVetFrm;
    public javax.swing.JLabel lbl2ApellidoVetFrm;
    public javax.swing.JLabel lblActivoVetFrm;
    public javax.swing.JLabel lblBuscarNombreVet;
    public javax.swing.JLabel lblCedulaVetFrm;
    public javax.swing.JLabel lblCodProfVetFrm;
    public javax.swing.JLabel lblDireccionVetFrm;
    public javax.swing.JLabel lblEmailVetFrm;
    public javax.swing.JLabel lblIdVetFrm;
    public javax.swing.JLabel lblLogoVet;
    public javax.swing.JLabel lblNombreVetFrm;
    public javax.swing.JLabel lblTelfVetFrm;
    public javax.swing.JLabel lblTitleVeterinarios;
    public javax.swing.JPanel panelDetalleVet;
    public javax.swing.JPanel panelIngresarDatosVet;
    public javax.swing.JPanel panelInservibleVet;
    public javax.swing.JPanel panelMantVet;
    public javax.swing.JTable tableVet;
    public javax.swing.JTextField txt1ApellidoVetFrm;
    public javax.swing.JTextField txt2ApellidoVetFrm;
    public javax.swing.JTextField txtBuscarNombreVet;
    public javax.swing.JTextField txtCedulaVetFrm;
    public javax.swing.JTextField txtCodProfVetFrm;
    public javax.swing.JTextArea txtDireccionVetFrm;
    public javax.swing.JTextField txtEmailVetFrm;
    public javax.swing.JTextField txtIdVetFrm;
    public javax.swing.JTextField txtNombreVetFrm;
    public javax.swing.JTextField txtTelfVetFrm;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
